version: ${project.version}

auth:
  enabled: true

ecs:
  service-name: tailscale-node
  essential-container-name: vpn-container
  host-name-env: TAILSCALE_HOSTNAME
  service-name-tag: ServiceName
  host-name-tag: Hostname
  run-by-tag: RunBy
  chat-id-tag: ChatId
  language-tag: Lang

aws:
  region-cities:
    'us-east-2': Ohio
    'us-east-1': N. Virginia
    'us-west-1': N. California
    'us-west-2': Oregon
    'af-south-1': Cape Town
    'ap-east-1': Hong Kong
    'ap-south-2': Hyderabad
    'ap-southeast-3': Jakarta
    'ap-southeast-5': Malaysia
    'ap-southeast-4': Melbourne
    'ap-southeast-7': Thailand
    'ap-south-1': Mumbai
    'ap-northeast-3': Osaka
    'ap-northeast-2': Seoul
    'ap-southeast-1': Singapore
    'ap-southeast-2': Sydney
    'ap-northeast-1': Tokyo
    'ca-central-1': Central
    'ca-west-1': Calgary
    'eu-central-1': Frankfurt
    'eu-west-1': Ireland
    'eu-west-2': London
    'eu-south-1': Milan
    'eu-west-3': Paris
    'eu-south-2': Spain
    'eu-north-1': Stockholm
    'eu-central-2': Zurich
    'il-central-1': Tel Aviv
    'me-south-1': Bahrain
    'me-central-1': UAE
    'sa-east-1': São Paulo
    'us-gov-east-1': US-East
    'us-gov-west-1': US-West
    'mx-central-1': Mexico
    'ap-east-2': Taipei
    'ap-southeast-6': Auckland
  region-countries:
    'us-east-2': US
    'us-east-1': US
    'us-west-1': US
    'us-west-2': US
    'af-south-1': ZA
    'ap-east-1': HK
    'ap-south-2': IN
    'ap-southeast-3': ID
    'ap-southeast-5': MY
    'ap-southeast-4': AU
    'ap-southeast-7': TH
    'ap-south-1': IN
    'ap-northeast-3': JP
    'ap-northeast-2': KR
    'ap-southeast-1': SG
    'ap-southeast-2': AU
    'ap-northeast-1': JP
    'ca-central-1': CA
    'ca-west-1': CA
    'eu-central-1': DE
    'eu-west-1': IE
    'eu-west-2': GB
    'eu-south-1': IT
    'eu-west-3': FR
    'eu-south-2': ES
    'eu-north-1': SE
    'eu-central-2': CH
    'il-central-1': IL
    'me-south-1': BH
    'me-central-1': AE
    'sa-east-1': BR
    'us-gov-east-1': US
    'us-gov-west-1': US
    'mx-central-1': MX
    'ap-east-2': TW
    'ap-southeast-6': NZ
