version: ${project.version}

s3:
  config-bucket: openvpn-server-s3
  config-root-dir: ecs-tailscale-node/config
  region-key: supported-regions.txt
  stack-output-parameters-key: vpn-ecs-resources-output-parameters.json

ecs:
  service-name: tailscale-node
  host-name-env: TAILSCALE_HOSTNAME
  host-name-tag: Hostname
  run-by-tag: RunBy
  health:
    interval-ms: 500
    timeout-sec: 60

aws:
  region-cities:
    us-east-2: Ohio
    us-east-1: N. Virginia
    us-west-1: N. California
    us-west-2: Oregon
    af-south-1: Cape Town
    ap-east-1: Hong Kong
    ap-south-2: Hyderabad
    ap-southeast-3: Jakarta
    ap-southeast-5: Malaysia
    ap-southeast-4: Melbourne
    ap-south-1: Mumbai
    ap-northeast-3: Osaka
    ap-northeast-2: Seoul
    ap-southeast-1: Singapore
    ap-southeast-2: Sydney
    ap-northeast-1: Tokyo
    ca-central-1: Central
    ca-west-1: Calgary
    eu-central-1: Frankfurt
    eu-west-1: Ireland
    eu-west-2: London
    eu-south-1: Milan
    eu-west-3: Paris
    eu-south-2: Spain
    eu-north-1: Stockholm
    eu-central-2: Zurich
    il-central-1: Tel Aviv
    me-south-1: Bahrain
    me-central-1: UAE
    sa-east-1: São Paulo
    us-gov-east-1: US-East
    us-gov-west-1: US-West