# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: VPN Bot Lambda CI-CD

env:
  S3_CONFIG_BUCKET_NAME: ${{ vars.S3_CONFIG_BUCKET_NAME }}
  S3_CONFIG_REGION: ${{ vars.CONFIG_BASE_REGION }}

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/main/java/**'
      - 'src/main/resources/**'
      - '.github/workflows/ci-cd.yml'
    branches:
      - main

jobs:
  ci-cd-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4

    - name: Set Up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'corretto'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build Lambda
      run: mvn clean package shade:shade
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ env.S3_CONFIG_REGION }}
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Upload Artifact To S3
      id: src-upload
      run: |
        POM_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        aws s3 cp target/vpnbot-${POM_VERSION}.jar s3://${{ env.S3_CONFIG_BUCKET_NAME }}/vpntgbot/vpnbot-${POM_VERSION}.jar
        echo "::set-output name=src_s3_key::vpntgbot/vpnbot-${POM_VERSION}.jar"

    - name: Update AWS Lambda
      run: |
        aws lambda update-function-code --function-name vpnbot --s3-bucket ${{ env.S3_CONFIG_BUCKET_NAME }} --s3-key "${{ steps.src-upload.outputs.src_s3_key }}"
      
