name: Deploy VPN Configurer Lambda Resources

on:
  workflow_dispatch:
    inputs:
      region:
        description: 'AWS Region'
        required: true
        default: eu-north-1

jobs:
  deploy-vpn-configurer-lambda:
    name: Deploy CloudFormation OpenVPN Telegram Bot Lambda
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ github.event.inputs.region }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Deploy Cloud Formation Stack
        id: deploy-cfn-stack
        uses: aws-actions/aws-cloudformation-github-deploy@v1.3.0
        with:
          name: openvpn-server-tgbot-cfn
          template: cloudformation/vpn-configurer-lambda.yml
          no-fail-on-empty-changeset: "1"
          capabilities: CAPABILITY_IAM

