name: Deploy VPN Configurer Lambda Resources

on:
  workflow_dispatch:
    inputs:
      region:
        description: 'AWS Region'
        required: true
        default: eu-north-1
      sources-bucket:
        description: 'S3 Bucket with sources of the lambda'
        required: true
        default: openvpn-server-s3

env:
  TG_BOT_USERNAME: ${{ vars.TG_BOT_USERNAME }}
  TG_SECRET_TOKEN_ID: ${{ vars.TG_SECRET_TOKEN_ID }}

jobs:
  deploy-vpn-configurer-lambda:
    name: Deploy CloudFormation OpenVPN Telegram Bot Lambda
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ github.event.inputs.region }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Upload TG Secret Token
        id: tg-secret-upload
        run: |
          if [ $(aws secretsmanager describe-secret --secret-id "${{ env.TG_SECRET_TOKEN_ID }}" --region ${{ github.event.inputs.region }} >/dev/null 2>&1; echo $?) -ne 0 ]; then
             aws secretsmanager create-secret --name ${{ env.TG_SECRET_TOKEN_ID }} --secret-string "${{ secrets.TG_SECRET_TOKEN }}" --region ${{ github.event.inputs.region }};
          fi
      - name: Deploy Cloud Formation Stack
        id: deploy-cfn-stack
        uses: aws-actions/aws-cloudformation-github-deploy@v1.3.0
        with:
          name: openvpn-server-tgbot-cfn
          template: cloudformation/vpn-configurer-lambda.yml
          no-fail-on-empty-changeset: "1"
          capabilities: CAPABILITY_IAM,CAPABILITY_NAMED_IAM
          parameter-overrides: 'LambdaSourcesBucketName=${{ github.event.inputs.sources-bucket }},EnvTgBotToken=${{ secrets.TG_BOT_TOKEN }},EnvTgBotUsername=${{ env.TG_BOT_USERNAME }},EnvTgBotSecretTokenId=${{ env.TG_SECRET_TOKEN_ID }}'

